name: deploy-watchtower

on:
  push:
    paths:
      - '.github/workflows/watchtower.yml'
      - 'watchtower/**'
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Tailscale
        uses: tailscale/github-action@ce41a99162202a647a4b24c30c558a567b926709
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          hostname: Github-actions
          version: 1.36.2

      - name: Start Deployment
        uses: aosus/docker-compose-gitops-action@v1
        with:
          remote_docker_host: ${{ secrets.server_address }}
          tailscale_ssh: true # no need for manual private and public keys
          compose_file_path: watchtower/docker-compose.yml
          args: -p watchtower up -d